services:
  buildhost:
    container_name: yosbuild
    hostname: yosbuild
    env_file:
      - docker-compose.env
    build:
      context: ./docker
      args:
        LFS_UID: $LFS_UID
        LFS_GID: $LFS_GID
        LFS_USER: $LFS_USER
    volumes:
      - yos-lfs:/mnt/lfs
      - yos-build:/home/$LFS_USER
      - ./Makefile:/home/$LFS_USER/Makefile:ro
      - ./config.mk:/home/$LFS_USER/config.mk:ro
      - ./makefiles:/home/$LFS_USER/makefiles:ro
      - ./patch:/home/$LFS_USER/patch:ro

volumes:
  yos-lfs:
  yos-build:
